using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace App7
{
    public class LoginPage : ContentPage
    {
        //ment to be empty for a reason because content gets generated by the Xamarin.Auth

        
    }
}
